# Generated by Django 4.2.1 on 2023-12-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanagement', '0002_city_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Улица')),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['house_number'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='housemanagement.city', verbose_name='Город'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['house_number'], name='housemanage_house_n_aabaad_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='housemanage_name_63b504_idx'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housemanagement.street', verbose_name='Улица'),
        ),
    ]
